import pandas as pd
from collections import Counter
from nltk import Tree

# --- Data Loading ---
agreement_file = '../SAP_stimuli/sap_items_Agreement.csv'
attachment_ambiguity_file = '../SAP_stimuli/sap_items_AttachmentAmbiguity.csv'
classic_gp_file = '../SAP_stimuli/sap_items_ClassicGP.csv'
filler_file = '../SAP_stimuli/sap_items_filler.csv'
relative_clause_file = '../SAP_stimuli/sap_items_RelativeClause.csv'

sap_filenames = [agreement_file, attachment_ambiguity_file,
                 classic_gp_file, filler_file, relative_clause_file]
sap_sentences = []
sap_parsed_sents = []
for sap_filename in sap_filenames:
    df = pd.read_csv(sap_filename)
    sap_sentences += df['Sentence'].tolist()
    sap_parsed_sents += df['berkeley_neural_parser_result'].tolist()

# The following code is generated by Claude Opus 4.5
# --- Rule Extraction ---


def extract_rules(tree):
    """
    Recursively extract CFG rules from an NLTK Tree.
    Returns two lists: syntactic_rules and lexical_rules.

    Syntactic rule: LHS -> RHS where RHS contains only non-terminals
                    e.g., "S -> NP VP"
    Lexical rule:   LHS -> RHS where RHS is a terminal (word)
                    e.g., "EX -> There"
    """
    syntactic_rules = []
    lexical_rules = []

    if isinstance(tree, Tree):
        lhs = tree.label()
        children = list(tree)

        # Check if this is a pre-terminal (parent of a word)
        if len(children) == 1 and isinstance(children[0], str):
            # Lexical rule: POS -> word
            lexical_rules.append(f"{lhs} -> {children[0]}")
        else:
            # Syntactic rule: collect child labels
            child_labels = []
            for child in children:
                if isinstance(child, Tree):
                    child_labels.append(child.label())
                else:
                    # Direct word child (unusual but possible)
                    child_labels.append(child)

            rhs = " ".join(child_labels)
            syntactic_rules.append(f"{lhs} -> {rhs}")

            # Recurse into children
            for child in children:
                if isinstance(child, Tree):
                    sub_syn, sub_lex = extract_rules(child)
                    syntactic_rules.extend(sub_syn)
                    lexical_rules.extend(sub_lex)

    return syntactic_rules, lexical_rules


# --- Process All Sentences ---
all_syntactic_rules = Counter()
all_lexical_rules = Counter()

for i, parsed_sent in enumerate(sap_parsed_sents):
    if pd.isna(parsed_sent):
        print(f"Warning: Skipping sentence {i} (no parse)")
        continue
    try:
        tree = Tree.fromstring(parsed_sent)
        syn_rules, lex_rules = extract_rules(tree)
        all_syntactic_rules.update(syn_rules)
        all_lexical_rules.update(lex_rules)
    except Exception as e:
        print(f"Error parsing sentence {i}: {e}")


# --- Output Results ---
print("=" * 60)
print(f"SYNTACTIC RULES (Non-terminal -> Non-terminals)")
print(f"Total unique: {len(all_syntactic_rules)}")
print("=" * 60)
for rule, count in all_syntactic_rules.most_common():
    print(f"{count:5d}  {rule}")

print("\n" + "=" * 60)
print(f"LEXICAL RULES (POS -> Word)")
print(f"Total unique: {len(all_lexical_rules)}")
print("=" * 60)
for rule, count in all_lexical_rules.most_common():
    print(f"{count:5d}  {rule}")

# --- Summary ---
print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)
print(f"Total sentences processed: {len(sap_parsed_sents)}")
print(f"Unique syntactic rules: {len(all_syntactic_rules)}")
print(f"Unique lexical rules: {len(all_lexical_rules)}")
print(
    f"Total unique rules: {len(all_syntactic_rules) + len(all_lexical_rules)}")

with open('syntactic_rules.txt', 'w') as f:
    f.write('\n'.join(f"{count}\t{rule}" for rule,
            count in all_syntactic_rules.most_common()))

with open('lexical_rules.txt', 'w') as f:
    f.write('\n'.join(f"{count}\t{rule}" for rule,
            count in all_lexical_rules.most_common()))
